# Generated by Django 4.2.30 on 2026-06-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('caminho_script', models.CharField(max_length=500)),
                ('argumentos', models.CharField(blank=True, max_length=500)),
                ('minuto', models.CharField(default='0', max_length=20)),
                ('hora', models.CharField(default='8', max_length=20)),
                ('dia_mes', models.CharField(default='*', max_length=20)),
                ('mes', models.CharField(default='*', max_length=20)),
                ('dia_semana', models.CharField(default='*', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa Agendada',
                'verbose_name_plural': 'Tarefas Agendadas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField()),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rodando', 'Rodando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='rodando', max_length=10)),
                ('saida', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('codigo_retorno', models.IntegerField(blank=True, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='agendador.tarefaagendada')),
            ],
            options={
                'verbose_name': 'Histórico de Execução',
                'verbose_name_plural': 'Históricos de Execução',
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
