# Generated by Django 4.2.30 on 2026-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0003_seed_configuracoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='dia_mes',
        ),
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='minuto',
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='dias_mes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='dias_semana',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='meses_execucao',
            field=models.CharField(blank=True, default='*', max_length=50),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='repetir_semanas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tarefaagendada',
            name='tipo_agendamento',
            field=models.CharField(choices=[('diario', 'Diário'), ('dias_uteis', 'Dias Úteis'), ('uma_vez', 'Uma Vez'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('intervalo', 'A cada X min')], default='diario', max_length=20),
        ),
    ]
