# Generated by Django 4.2.30 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0004_remove_tarefaagendada_dia_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaagendada',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarefaagendada',
            name='tipo_agendamento',
            field=models.CharField(choices=[('diario', 'Diário'), ('dias_uteis', 'Dias Úteis'), ('uma_vez', 'Uma Vez'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('intervalo', 'Por Intervalo')], default='diario', max_length=20),
        ),
    ]
