# Generated by Django 4.2.30 on 2026-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0005_add_observacoes_to_tarefaagendada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaagendada',
            name='modulo',
            field=models.CharField(blank=True, choices=[('', '— Selecione —'), ('ambulatorial', 'Ambulatorial'), ('urgencia', 'Urgência'), ('leitos_aih', 'Leitos AIH'), ('leitos', 'Leitos'), ('pre_hospitalar', 'Pré-Hospitalar'), ('indicadores', 'Indicadores')], max_length=20),
        ),
    ]
