# Generated by Django 4.2.30 on 2026-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0006_add_modulo_to_tarefaagendada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaagendada',
            name='assunto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
