# Generated by Django 4.2.30 on 2026-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0007_add_assunto_to_tarefaagendada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefaagendada',
            name='assunto',
        ),
    ]
