# Generated by Django 4.2.30 on 2026-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador', '0008_remove_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaagendada',
            name='modulo',
            field=models.CharField(blank=True, choices=[('', '— Selecione —'), ('ambulatorial', 'Ambulatorial'), ('urgencia', 'Urgência'), ('leitos_aih', 'Leitos AIH'), ('leitos', 'Leitos'), ('pre_hospitalar', 'Pré-Hospitalar'), ('indicadores', 'Indicadores'), ('agendamentos', 'Agendamentos'), ('naep', 'NAEP'), ('nucleo_oncologia', 'Núcleo de Oncologia'), ('oncologia', 'Oncologia')], max_length=20),
        ),
    ]
