# Generated by Django 4.2.30 on 2026-06-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('ambulatorial', 'Ambulatorial'), ('urgencia', 'Urgência'), ('leitos_aih', 'Leitos AIH'), ('leitos', 'Leitos'), ('pre_hospitalar', 'Pré-Hospitalar'), ('indicadores', 'Indicadores'), ('outros', 'Outros')], max_length=20, verbose_name='Módulo')),
                ('modulo_outros', models.CharField(blank=True, max_length=200, verbose_name='Módulo (outros)')),
                ('nome_arquivo', models.CharField(max_length=300, verbose_name='Nome do Arquivo')),
                ('caminho_tableau', models.TextField(blank=True, verbose_name='Caminho Tableau')),
                ('link_tableau', models.URLField(blank=True, max_length=500, verbose_name='Link do Tableau')),
                ('setor_solicitante', models.CharField(blank=True, max_length=200, verbose_name='Setor Solicitante')),
                ('nome_solicitante', models.CharField(blank=True, max_length=200, verbose_name='Nome do Solicitante')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data de Solicitação')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Data de Homologação')),
                ('data_aceite', models.DateField(blank=True, null=True, verbose_name='Data de Aceite')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['nome_arquivo'],
            },
        ),
        migrations.CreateModel(
            name='FonteDeDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('conexao', models.CharField(blank=True, max_length=300, verbose_name='Conexão')),
                ('banco_dados', models.CharField(blank=True, max_length=300, verbose_name='Banco de Dados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
            },
        ),
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilhas', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'Histórias',
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtros',
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
            },
        ),
    ]
