# Generated by Django 4.2.30 on 2026-06-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDeDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('conexao', models.CharField(blank=True, max_length=200, verbose_name='Conexão (servidor)')),
                ('banco', models.CharField(blank=True, max_length=200)),
                ('tipo_conexao', models.CharField(choices=[('tempo_real', 'Em tempo real'), ('extracao', 'Extração')], default='extracao', max_length=20)),
                ('relacao_conexoes', models.TextField(blank=True, verbose_name='Relação de conexões')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'Histórias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PastaDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasta de Trabalho',
                'verbose_name_plural': 'Pastas de Trabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilhas', to='paineis.pastadetrabalho')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='paineis.projeto'),
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('regras', models.TextField(blank=True, verbose_name='Regras de negócio')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='paineis.pastadetrabalho')),
                ('planilhas', models.ManyToManyField(blank=True, related_name='paineis_vinculados', to='paineis.planilha')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(blank=True, max_length=200, verbose_name='Seção')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='paineis/planilhas/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('planilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='paineis.planilha')),
            ],
            options={
                'verbose_name': 'Imagem da Planilha',
                'verbose_name_plural': 'Imagens da Planilha',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(blank=True, max_length=200, verbose_name='Seção')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='paineis/paineis/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='paineis.painel')),
            ],
            options={
                'verbose_name': 'Imagem do Painel',
                'verbose_name_plural': 'Imagens do Painel',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(blank=True, max_length=200, verbose_name='Seção')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='paineis/historias/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='paineis.historia')),
            ],
            options={
                'verbose_name': 'Imagem da História',
                'verbose_name_plural': 'Imagens da História',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='paineis/fontes/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Imagem da Fonte',
                'verbose_name_plural': 'Imagens da Fonte',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.AddField(
            model_name='historia',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='paineis.pastadetrabalho'),
        ),
        migrations.AddField(
            model_name='fontededados',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='paineis.pastadetrabalho'),
        ),
        migrations.CreateModel(
            name='FiltroFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('detalhes', models.TextField(blank=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='paineis.fontededados')),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtros',
            },
        ),
    ]
