# Generated by Django 4.2.30 on 2026-06-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastadetrabalho',
            options={'ordering': ['nome'], 'verbose_name': 'Dados do Tableau', 'verbose_name_plural': 'Dados do Tableau'},
        ),
        migrations.RemoveField(
            model_name='pastadetrabalho',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pastadetrabalho',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='local_tableau_server',
            field=models.CharField(blank=True, max_length=500, verbose_name='Local Tableau Server'),
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='modulo',
            field=models.CharField(blank=True, choices=[('', '— Selecione —'), ('ambulatorial', 'Ambulatorial'), ('urgencia', 'Urgência'), ('leitos_aih', 'Leitos AIH'), ('leitos', 'Leitos'), ('pre_hospitalar', 'Pré-Hospitalar'), ('indicadores', 'Indicadores'), ('naep', 'NAEP'), ('nucleo_oncologia', 'Núcleo de Oncologia'), ('oncologia', 'Oncologia'), ('outros', 'Outros')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='modulo_outro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Módulo (outro)'),
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='setor_solicitante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Setor Solicitante'),
        ),
        migrations.AddField(
            model_name='pastadetrabalho',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='pastadetrabalho',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='RegistroDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desenvolvido', 'Desenvolvido por'), ('atualizado', 'Atualizado por')], default='desenvolvido', max_length=20)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='paineis.pastadetrabalho')),
            ],
            options={
                'verbose_name': 'Registro de Desenvolvimento',
                'verbose_name_plural': 'Registros de Desenvolvimento',
                'ordering': ['data', 'pk'],
            },
        ),
    ]
