# Generated by Django 4.2.30 on 2026-06-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='fontededados',
            name='conexao',
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='paineis.servidor')),
            ],
            options={
                'verbose_name': 'Banco de Dados',
                'verbose_name_plural': 'Bancos de Dados',
                'ordering': ['nome'],
                'unique_together': {('servidor', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='fontededados',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paineis.servidor', verbose_name='Conexão'),
        ),
        migrations.AlterField(
            model_name='fontededados',
            name='banco_dados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paineis.banco', verbose_name='Banco de Dados'),
        ),
    ]
