# Generated by Django 4.2.30 on 2026-06-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0002_servidor_remove_fontededados_conexao_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'ordering': ['pk'],
            },
        ),
    ]
