# Generated by Django 4.2.30 on 2026-06-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0003_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='numero',
            field=models.CharField(default='', max_length=50, verbose_name='Número da Versão'),
        ),
        migrations.CreateModel(
            name='RegistroVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_desenvolvedor', models.CharField(max_length=200, verbose_name='Nome do(a) Desenvolvedor(a)')),
                ('data_desenvolvimento', models.DateField(verbose_name='Data do Desenvolvimento')),
                ('acoes_realizadas', models.TextField(verbose_name='Ações Realizadas')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='paineis.versao')),
            ],
            options={
                'verbose_name': 'Registro de Versão',
                'verbose_name_plural': 'Registros de Versão',
                'ordering': ['data_desenvolvimento', 'pk'],
            },
        ),
    ]
