# Generated by Django 4.2.30 on 2026-06-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0004_versao_numero_registroversao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fontededados',
            name='banco_dados',
        ),
        migrations.RemoveField(
            model_name='fontededados',
            name='servidor',
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_dados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paineis.banco', verbose_name='Banco de Dados')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='paineis.fontededados')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paineis.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
            },
        ),
    ]
