from Amb_Cotas_Metodos import ApagarDados, ExtrairDados, IncluirDados, conexaoMRA, conexaoProducao, logger
############################################################################################################################################
if __name__ == "__main__":

    logger.info(f"--> INICIOU ROTINA ApagarDados.")
    ApagarDados("TB_RESUMO_AGENDAMENTO",conexaoMRA)    
    logger.info(f"--> FINALIZOU ROTINA ApagarDados.")  
    logger.info(f"--> INICIOU ROTINA DE CARGA - TB_AGENDAMENTOS.")
    #Para atender aos relatorios tempo de cuidar que serao criados só preciso do ano de 2026.    
    comando = f'''
                    SELECT 
                        MONTH(HORARIO.DATA_AGENDA)				MES,
                        YEAR(HORARIO.DATA_AGENDA)				ANO,
                        'EXAME'									TIPO,
                        UNIDADE_EXECUTANTE.COD_UNIDADE			CODIGO_EXECUTANTE,
                        UNIDADE_EXECUTANTE.UNIDADE_FANTASIA		UNIDADE_EXECUTANTE,
                        UNIDADE_SOLICITANTE.COD_UNIDADE			CODIGO_SOLICITANTE,
                        UNIDADE_SOLICITANTE.UNIDADE_FANTASIA	UNIDADE_SOLICITANTE,
                        GRUPO_COTA.ID_GRUPO_COTA				CODIGO_RECURSO,
                        GRUPO_COTA.NOME_GRUPO_COTA				NOME_RECURSO,
                        MIN(CAST(AGENDA.IDADE_INI AS INT))		IDADE_INICIAL, 
                        MIN(CAST(AGENDA.IDADE_FIM AS INT))		IDADE_FINAL,
                        COUNT(CASE WHEN HORARIO.ID_MOTIVO = 0 THEN HORARIO.ID_AGE_EXAME_HOR END) AS OFERTA,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE <> 0 AND HORARIO.ID_MOTIVO  = 0 AND HORARIO.FLG_ND <> 'S' AND HORARIO.FLG_BOLSAO <> 'S' THEN HORARIO.ID_AGE_EXAME_HOR 	END) AGENDAMENTO_POR_COTA,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE<> 0 AND HORARIO.FLG_ND='S' THEN HORARIO.ID_AGE_EXAME_HOR END) AS AGENDAMENTO_NAO_DISTRIBUIDO,	
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE<> 0 AND HORARIO.FLG_BOLSAO='S' AND HORARIO.ID_MOTIVO= 0 THEN HORARIO.ID_AGE_EXAME_HOR END) AS AGENDAMENTO_BOLSAO,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE <> 0 THEN HORARIO.ID_AGE_EXAME_HOR END) AGENDAMENTO_TOTAL,
                        COUNT(CASE WHEN HORARIO.BLOQUEADO = 'S' THEN HORARIO.ID_AGE_EXAME_HOR END) AGENDAMENTO_BLOQUEADO
                    FROM 
                        AMB_AGE_EXAME_HOR HORARIO
                    LEFT JOIN AMB_AGE_EXAME				 AS AGENDA					 ON AGENDA.ID_AGE_EXAME						    = HORARIO.ID_AGE_EXAME
                    LEFT JOIN ADMAMB_ADM_UNIDADE         AS UNIDADE_EXECUTANTE       ON UNIDADE_EXECUTANTE.COD_UNIDADE				= HORARIO.COD_UNIDADE_EXECUTANTE
                    LEFT JOIN ADMAMB_ADM_UNIDADE         AS UNIDADE_SOLICITANTE		 ON UNIDADE_SOLICITANTE.COD_UNIDADE				= HORARIO.COD_UNIDADE_SOLICITANTE
                    LEFT JOIN AMB_ADM_UNIDADE_REGIOES    AS REGIAO_SAUDE_EXECUTANTE  ON LEFT(REGIAO_SAUDE_EXECUTANTE.CODMUNGEST,6)	= LEFT(UNIDADE_EXECUTANTE.CODMUNGEST,6)
                    LEFT JOIN AMB_DRS                    AS DRS_EXECUTANTE			 ON DRS_EXECUTANTE.COD_DRS						= REGIAO_SAUDE_EXECUTANTE.COD_DRS
                    LEFT JOIN AMB_GRUPO_COTA             AS GRUPO_COTA				 ON GRUPO_COTA.ID_GRUPO_COTA					= HORARIO.ID_GRUPO_COTA
                    LEFT JOIN AMB_EXAME1                 AS EXAME					 ON EXAME.ID_EXAME								= HORARIO.ID_EXAME
                    WHERE YEAR(HORARIO.DATA_AGENDA) = 2026
                    GROUP BY 	
                        MONTH(HORARIO.DATA_AGENDA),	
                        YEAR(HORARIO.DATA_AGENDA),
                        UNIDADE_EXECUTANTE.COD_UNIDADE,
                        UNIDADE_EXECUTANTE.UNIDADE_FANTASIA,
                        UNIDADE_SOLICITANTE.COD_UNIDADE,
                        UNIDADE_SOLICITANTE.UNIDADE_FANTASIA,	
                        GRUPO_COTA.ID_GRUPO_COTA,
                        GRUPO_COTA.NOME_GRUPO_COTA				

                    UNION ALL

                    SELECT 
                        MONTH(HORARIO.DATA_AGENDA)				MES,
                        YEAR(HORARIO.DATA_AGENDA)				ANO,
                        'CONSULTA'								TIPO,
                        UNIDADE_EXECUTANTE.COD_UNIDADE			CODIGO_EXECUTANTE,
                        UNIDADE_EXECUTANTE.UNIDADE_FANTASIA		UNIDADE_EXECUTANTE,
                        UNIDADE_SOLICITANTE.COD_UNIDADE			CODIGO_SOLICITANTE,
                        UNIDADE_SOLICITANTE.UNIDADE_FANTASIA	UNIDADE_SOLICITANTE,
                        ESPECIALIDADE.ID_ESPECIALIDADE			CODIGO_RECURSO,
                        UPPER(ESPECIALIDADE.NOME_ESPECIALIDADE)	NOME_RECURSO,
                        MIN(CAST(AGENDA.IDADE_INI AS INT))		IDADE_INICIAL, 
                        MIN(CAST(AGENDA.IDADE_FIM AS INT))		IDADE_FINAL,
                        COUNT(CASE WHEN HORARIO.ID_MOTIVO = 0 THEN HORARIO.ID_AGE_CONSULTA_HOR END) AS OFERTA,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE <> 0 AND HORARIO.ID_MOTIVO  = 0 AND HORARIO.FLG_ND <> 'S' AND HORARIO.FLG_BOLSAO <> 'S' THEN HORARIO.ID_AGE_CONSULTA_HOR 	END) AGENDAMENTO_POR_COTA,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE<> 0 AND HORARIO.FLG_ND='S' THEN HORARIO.ID_AGE_CONSULTA_HOR END) AS AGENDAMENTO_NAO_DISTRIBUIDO,	
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE<> 0 AND HORARIO.FLG_BOLSAO='S' AND HORARIO.ID_MOTIVO= 0 THEN HORARIO.ID_AGE_CONSULTA_HOR END) AS AGENDAMENTO_BOLSAO,
                        COUNT(CASE WHEN HORARIO.COD_PACIENTE <> 0 THEN HORARIO.ID_AGE_CONSULTA_HOR END) AGENDAMENTO_TOTAL,
                        COUNT(CASE WHEN HORARIO.BLOQUEADO = 'S' THEN HORARIO.ID_AGE_CONSULTA_HOR END) AGENDAMENTO_BLOQUEADO
                    FROM 
                        AMB_AGE_CONSULTA_HOR HORARIO
                    LEFT JOIN AMB_AGE_CONSULTA			AGENDA					ON AGENDA.ID_AGE_CONSULTA					    = HORARIO.ID_AGE_CONSULTA
                    LEFT JOIN ADMAMB_ADM_UNIDADE        UNIDADE_EXECUTANTE      ON UNIDADE_EXECUTANTE.COD_UNIDADE				= HORARIO.COD_UNIDADE_EXECUTANTE
                    LEFT JOIN ADMAMB_ADM_UNIDADE        UNIDADE_SOLICITANTE		ON UNIDADE_SOLICITANTE.COD_UNIDADE				= HORARIO.COD_UNIDADE_SOLICITANTE
                    LEFT JOIN AMB_ADM_UNIDADE_REGIOES   REGIAO_SAUDE_EXECUTANTE ON LEFT(REGIAO_SAUDE_EXECUTANTE.CODMUNGEST,6)	= LEFT(UNIDADE_EXECUTANTE.CODMUNGEST,6)
                    LEFT JOIN AMB_DRS                   DRS_EXECUTANTE			ON DRS_EXECUTANTE.COD_DRS						= REGIAO_SAUDE_EXECUTANTE.COD_DRS
                    LEFT JOIN AMB_ESPECIALIDADE			ESPECIALIDADE			ON ESPECIALIDADE.ID_ESPECIALIDADE				= HORARIO.ID_ESPECIALIDADE

                    WHERE	YEAR(HORARIO.DATA_AGENDA) = 2026
                    AND		HORARIO.TIPO = 'P'
                    AND		HORARIO.ID_MOTIVO = 0
                    GROUP BY 	
                        MONTH(HORARIO.DATA_AGENDA),	
                        YEAR(HORARIO.DATA_AGENDA),
                        UNIDADE_EXECUTANTE.COD_UNIDADE,
                        UNIDADE_EXECUTANTE.UNIDADE_FANTASIA,
                        UNIDADE_SOLICITANTE.COD_UNIDADE,
                        UNIDADE_SOLICITANTE.UNIDADE_FANTASIA,	
                        ESPECIALIDADE.ID_ESPECIALIDADE,
                        ESPECIALIDADE.NOME_ESPECIALIDADE	
               '''    
    dfSOLICITACAO = ExtrairDados(conexaoProducao,comando)
    IncluirDados(dfSOLICITACAO,"TB_RESUMO_AGENDAMENTO",conexaoMRA)    
    logger.info(f"--> FINALIZOU ROTINA DE CARGA - TB_RESUMO_AGENDAMENTO.")      